name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.20.2
  logger: ^2.5.0
  connectivity_plus: ^6.1.4
  smooth_page_indicator: ^1.2.1
  flutter_native_splash: ^2.4.4
  lottie: ^3.3.1
  readmore: ^3.0.0

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State Management + Local Storage
  get: ^4.7.2
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.3.0

  # Project Specific
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/logos/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/images/products/
    - assets/images/reviews/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 800