// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqBbH_lC50crLLLRjyQ3uOe7zsWvWZLlo',
    appId: '1:804818491652:web:48b4b36f924292bd3e1851',
    messagingSenderId: '804818491652',
    projectId: 'ecommerceapp-f6700',
    authDomain: 'ecommerceapp-f6700.firebaseapp.com',
    storageBucket: 'ecommerceapp-f6700.firebasestorage.app',
    measurementId: 'G-ZHMZWRM2K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjdAoXE1957hlZ0iVLHUVff46t2H0cQS8',
    appId: '1:804818491652:android:f75edb565c2d2ea13e1851',
    messagingSenderId: '804818491652',
    projectId: 'ecommerceapp-f6700',
    storageBucket: 'ecommerceapp-f6700.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvbiqVWQLk-0mD8GpOP9CMmgurEnFQtwI',
    appId: '1:804818491652:ios:b56cc10057fef9983e1851',
    messagingSenderId: '804818491652',
    projectId: 'ecommerceapp-f6700',
    storageBucket: 'ecommerceapp-f6700.firebasestorage.app',
    androidClientId: '804818491652-1s5ftr07kkaeau6vjsd17j0stej1mluq.apps.googleusercontent.com',
    iosClientId: '804818491652-k1j0bh0lg9cmv5tkdh5lp2cvb78jq7je.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

}